### ISSUE TITLE
[12주차] 백준 문제 4개 풀기

### ISSUE THREAD

**Issue by bestlalala** [bestlalala/Algorithm_study#29]
# [12주차] 백준 문제 4개 풀기

문제 링크: https://www.acmicpc.net/workbook/view/7315

- [x] [N과 M (1)](https://www.acmicpc.net/problem/15649)
- [x] [N-Queen](https://www.acmicpc.net/problem/9663)
- [x] [부분수열의 합](https://www.acmicpc.net/problem/1182)
- [x] [N과 M (2)](https://www.acmicpc.net/problem/15650)
